### ISSUE TITLE
How to build Longan? Maven?

### ISSUE THREAD

**Issue by divlv** [Zarkonnen/Longan#1]
Hello!
I'm new to java ocr techs, so, could you please explain how to build your project correctly?
Any version with Maven's pom, or...?

Thanks.

**Comment by Zarkonnen** [comment]
So the way I build it is that I pretty much add the sources into 
Eclipse/NetBeans/whatever and hit Build. There aren't really any/many 
dependencies to deal with.
- David

**Comment by Wockito** [comment]
I tried searching for documentation but didn't find any. Can you please point me to a link of documentation

**Comment by GuiSim** [comment]
This seems to be a dead project.

**Comment by Zarkonnen** [comment]
It has no dependencies, so if you just compile the contents of src, it'll work.

**Comment by Zarkonnen** [comment]
Eg I just import it into NetBeans as a project with existing sources, set the base directory to be the project directory, and hit run, and it works.
